a=[
'James Cameron',
'Peter Jackson',
'Christopher Nolan',
'Michael Bay',
'Gore Verbinski',
'Chris Columbus',
'Sam Raimi',
'Sam Mendes',
'Roland Emmerich',
'Zack Snyder',
'Bryan Singer',
'Steven Spielberg',
'Barry Sonnenfeld',
'Lilly Wachowski',
'Lana Wachowski',
'Robert Zemeckis',
'M. Night Shyamalan',
'Martin Campbell',
'Ron Howard',
'Tim Burton',
'Jay Roach',
'Wolfgang Petersen',
'Shawn Levy',
'Brett Ratner',
'David Fincher',
'Garry Marshall',
'Marc Forster',
'Ridley Scott',
'Ang Lee',
'Doug Liman',
'Tom Shadyac',
'Todd Phillips',
'Edward Zwick',
'Dennis Dugan',
'Tony Scott',
'Simon West',
'Guy Ritchie',
'Quentin Tarantino'
]
b=[
'Christopher Nolan',
'Quentin Tarantino',
'Wes Anderson',
'Martin Scorsese',
'David Fincher',
'Peter Jackson',
'James Cameron',
'Francis Ford Coppola',
'Alfred Hitchcock',
'Danny Boyle',
'Richard Linklater',
'Lasse Hallström',
'Steven Spielberg',
'Clint Eastwood',
'Robert Zemeckis',
'Sam Mendes',
]
c=list(set(a)&set(b))
for i in c:
    print(i)